#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libqxp
Version  : 0.0.2
Release  : 6
URL      : https://dev-www.libreoffice.org/src/libqxp-0.0.2.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libqxp-0.0.2.tar.xz
Summary  : No summary provided
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libqxp-bin = %{version}-%{release}
Requires: libqxp-lib = %{version}-%{release}
Requires: libqxp-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)

%description
libqxp is a library and a set of tools for reading and converting
QuarkXPress file format. It supports versions 3.1-4.1 currently.

%package bin
Summary: bin components for the libqxp package.
Group: Binaries
Requires: libqxp-license = %{version}-%{release}

%description bin
bin components for the libqxp package.


%package dev
Summary: dev components for the libqxp package.
Group: Development
Requires: libqxp-lib = %{version}-%{release}
Requires: libqxp-bin = %{version}-%{release}
Provides: libqxp-devel = %{version}-%{release}
Requires: libqxp = %{version}-%{release}

%description dev
dev components for the libqxp package.


%package doc
Summary: doc components for the libqxp package.
Group: Documentation

%description doc
doc components for the libqxp package.


%package lib
Summary: lib components for the libqxp package.
Group: Libraries
Requires: libqxp-license = %{version}-%{release}

%description lib
lib components for the libqxp package.


%package license
Summary: license components for the libqxp package.
Group: Default

%description license
license components for the libqxp package.


%prep
%setup -q -n libqxp-0.0.2
cd %{_builddir}/libqxp-0.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592624004
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1592624004
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libqxp
cp %{_builddir}/libqxp-0.0.2/COPYING %{buildroot}/usr/share/package-licenses/libqxp/9744cedce099f727b327cd9913a1fdc58a7f5599
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qxp2raw
/usr/bin/qxp2svg
/usr/bin/qxp2text

%files dev
%defattr(-,root,root,-)
/usr/include/libqxp-0.0/libqxp/QXPDocument.h
/usr/include/libqxp-0.0/libqxp/QXPPathResolver.h
/usr/include/libqxp-0.0/libqxp/libqxp.h
/usr/include/libqxp-0.0/libqxp/libqxp_api.h
/usr/lib64/libqxp-0.0.so
/usr/lib64/pkgconfig/libqxp-0.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libqxp/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqxp-0.0.so.0
/usr/lib64/libqxp-0.0.so.0.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libqxp/9744cedce099f727b327cd9913a1fdc58a7f5599
